// <auto-generated />
using System;
using BasicSocialMedia.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BasicSocialMedia.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723031142_AddCognitoSubject")]
    partial class AddCognitoSubject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlockedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlockerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BlockedUserId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteBy");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModificationBy");

                    b.HasIndex("BlockerId", "BlockedUserId")
                        .IsUnique();

                    b.ToTable("Block");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Bookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookmarkFolderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TweetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookmarkFolderId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteBy");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModificationBy");

                    b.HasIndex("TweetId");

                    b.HasIndex("UserId", "TweetId")
                        .IsUnique();

                    b.ToTable("Bookmark");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.BookmarkFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteBy");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModificationBy");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique();

                    b.ToTable("BookmarkFolder");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.DirectMessageChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParticipantOneId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantTwoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteBy");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModificationBy");

                    b.HasIndex("ParticipantTwoId");

                    b.HasIndex("ParticipantOneId", "ParticipantTwoId")
                        .IsUnique();

                    b.ToTable("DirectMessageChat");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Follow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FollowingId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteBy");

                    b.HasIndex("FollowingId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModificationBy");

                    b.HasIndex("FollowerId", "FollowingId")
                        .IsUnique();

                    b.ToTable("Follow");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Hashtag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteBy");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModificationBy");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Hashtag");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Like", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TweetId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "TweetId");

                    b.HasIndex("TweetId");

                    b.ToTable("Like");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePublicId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TweetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserProfilePictureId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteBy");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("MessageId");

                    b.HasIndex("ModificationBy");

                    b.HasIndex("TweetId");

                    b.HasIndex("UserProfilePictureId")
                        .IsUnique();

                    b.ToTable("Media");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageContent")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteBy");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModificationBy");

                    b.HasIndex("SenderId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotificationContent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteBy");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModificationBy");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Tweet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentTweetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuoteTweetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteBy");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModificationBy");

                    b.HasIndex("ParentTweetId");

                    b.HasIndex("QuoteTweetId");

                    b.ToTable("Tweet");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.TweetHashtag", b =>
                {
                    b.Property<Guid>("TweetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HashtagId")
                        .HasColumnType("uuid");

                    b.HasKey("TweetId", "HashtagId");

                    b.HasIndex("HashtagId");

                    b.ToTable("TweetHashtag");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CognitoSubject")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CognitoSubject")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeleteBy");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModificationBy");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Block", b =>
                {
                    b.HasOne("BasicSocialMedia.Domain.Entities.User", "BlockedUser")
                        .WithMany()
                        .HasForeignKey("BlockedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", "Blocker")
                        .WithMany()
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DeleteBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ModificationBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BlockedUser");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Bookmark", b =>
                {
                    b.HasOne("BasicSocialMedia.Domain.Entities.BookmarkFolder", null)
                        .WithMany("Bookmarks")
                        .HasForeignKey("BookmarkFolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DeleteBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ModificationBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.Tweet", "Tweet")
                        .WithMany("Bookmarks")
                        .HasForeignKey("TweetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tweet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.BookmarkFolder", b =>
                {
                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DeleteBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ModificationBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.DirectMessageChat", b =>
                {
                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DeleteBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ModificationBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", "ParticipantOne")
                        .WithMany()
                        .HasForeignKey("ParticipantOneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", "ParticipantTwo")
                        .WithMany()
                        .HasForeignKey("ParticipantTwoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParticipantOne");

                    b.Navigation("ParticipantTwo");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Follow", b =>
                {
                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DeleteBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", "Follower")
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", "Following")
                        .WithMany()
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ModificationBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Hashtag", b =>
                {
                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DeleteBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ModificationBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Like", b =>
                {
                    b.HasOne("BasicSocialMedia.Domain.Entities.Tweet", "Tweet")
                        .WithMany("LikedByUsers")
                        .HasForeignKey("TweetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tweet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Media", b =>
                {
                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DeleteBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.Message", "Message")
                        .WithMany("Media")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ModificationBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.Tweet", "Tweet")
                        .WithMany("Media")
                        .HasForeignKey("TweetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", "User")
                        .WithOne("ProfilePicture")
                        .HasForeignKey("BasicSocialMedia.Domain.Entities.Media", "UserProfilePictureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Message");

                    b.Navigation("Tweet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Message", b =>
                {
                    b.HasOne("BasicSocialMedia.Domain.Entities.DirectMessageChat", "DirectMessageChat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DeleteBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ModificationBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DirectMessageChat");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Notification", b =>
                {
                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DeleteBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ModificationBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Tweet", b =>
                {
                    b.HasOne("BasicSocialMedia.Domain.Entities.User", "TweetAuthor")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DeleteBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ModificationBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.Tweet", "ParentTweet")
                        .WithMany("Replies")
                        .HasForeignKey("ParentTweetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.Tweet", "QuoteTweet")
                        .WithMany()
                        .HasForeignKey("QuoteTweetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentTweet");

                    b.Navigation("QuoteTweet");

                    b.Navigation("TweetAuthor");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.TweetHashtag", b =>
                {
                    b.HasOne("BasicSocialMedia.Domain.Entities.Hashtag", "Hashtag")
                        .WithMany()
                        .HasForeignKey("HashtagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BasicSocialMedia.Domain.Entities.Tweet", "Tweet")
                        .WithMany("TweetHashtags")
                        .HasForeignKey("TweetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hashtag");

                    b.Navigation("Tweet");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.User", b =>
                {
                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DeleteBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ModificationBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BasicSocialMedia.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.BookmarkFolder", b =>
                {
                    b.Navigation("Bookmarks");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.DirectMessageChat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Message", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.Tweet", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("LikedByUsers");

                    b.Navigation("Media");

                    b.Navigation("Replies");

                    b.Navigation("TweetHashtags");
                });

            modelBuilder.Entity("BasicSocialMedia.Domain.Entities.User", b =>
                {
                    b.Navigation("ProfilePicture");
                });
#pragma warning restore 612, 618
        }
    }
}
